# Generated by Django 5.2 on 2025-04-04 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('bank_account_no', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=10)),
                ('address', models.TextField()),
                ('projects_done_in_year', models.IntegerField()),
                ('salary', models.FloatField()),
                ('term_in_company', models.IntegerField()),
            ],
        ),
    ]
